### PR TITLE
TYPO3 7 LTS compatibility

### PR DESCRIPTION
**Pull request by grimmcreative**
Now compatible with TYPO3 Version 7.6.x LTS

### CODE REVIEW

**Comment by dohomi** [comment]
Hi @grimmcreative thanks for your PR I will merge it as it is. I currently out of TYPO3 7.x so I'll trust you in this one

**Comment by dohomi** [comment]
Thanks for this one!

**Comment by grimmcreative** [comment]
Thanks for merging it. 
Its completely Tested and already in Production.

**Comment by dohomi** [comment]
I uploaded the TER version 2.0.0 with this changes just now.

**Pull request merged**
